import { Urbanist } from 'next/font/google';
import "./globals.css";
import { ThemeProvider } from '@/components/theme-provider';
import InitAuth from './initAuth';

const urbanist = Urbanist({
  subsets: ['latin'],
  display: 'swap',
})

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "The Gourmet Spot",
  description:
    " Discover a seamless way to order your favorite meals with our intuitive app. Browse menus from local restaurants, customize your orders, and track them in real time. Whether you want delivery or pickup, our app makes it fast and simple.",
  icons: {
    icon: "/logo.png",
    apple: "/logo.png",
    shortcut: "/logo.png",
  },
  openGraph: {
    title: "The Gourmet Spot",
    description:
      "From appetizers to desserts, our meal ordering app brings you fresh, delicious food in just a few taps. Save your favorites, manage your cart, and enjoy secure, convenient checkout. Perfect for busy schedules, quick cravings, or meal planning.",
    url: "https://www.southernliving.com/thmb/YkeCguqjvAS-fj2DRtXzl-qzdEQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/07172024_Fancypants_Andrew-Cebulka-17221-bf58a5e4247941a4860d620fc72b22ed.jpg", // update with your actual URL
    siteName: "The Gourmet Spot",
    images: [
      {
        url: "https://www.southernliving.com/thmb/YkeCguqjvAS-fj2DRtXzl-qzdEQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/07172024_Fancypants_Andrew-Cebulka-17221-bf58a5e4247941a4860d620fc72b22ed.jpg", // change this to your OG image URL
        width: 1200,
        height: 630,
        alt: "The Gourmet Spot",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "The Gourmet Spot",
    description:
      "Delicious meals, just a few taps away. Browse, order, and enjoy!",
    images: "https://www.southernliving.com/thmb/YkeCguqjvAS-fj2DRtXzl-qzdEQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/07172024_Fancypants_Andrew-Cebulka-17221-bf58a5e4247941a4860d620fc72b22ed.jpg", // same image as above
    creator: "@yourhandle", // optional
  },
};

export default function RootLayout({ children }) {
  return (
     <html lang="en" suppressHydrationWarning className={urbanist.className}>
      <body className={urbanist.className}>
        <InitAuth />
      <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
